### ISSUE TITLE
Can't configure but have /usr/inlude/taglib

### ISSUE THREAD

**Issue by 97-109-107** [ryanflannery/vitunes#43]
I've compiled TagLib from source on my Debian Squeeze Linux 3.8 amd64. I can see the files **/usr/include/taglib**. However, I can't go through configure.sh cleanly. It fails to detect taglib. When looking into the script I tried running **'pkg-config --exists taglib'** to diagnose the issue. It doesn't return anything. I guess I could move on with using '-C /usr/include/taglib' when running make but it yields make: **No rule to make target `install'.  Stop.**. If I understand correctly, I need a makefile to be generated from configure.sh but I can't as it fails as described above. Where did I make a mistake?

(I also tried adding **tag_c.hh** directly into the vitunes source folder and editing the headers, then however I get a lot **ecmd_tag.c:(.text+0x482): undefined reference to `taglib_set_strings_unicode'** etc. Which leads me to believe that this approach won't get me very far.)

Thank you

**Comment by septimiul891-pixel** [comment]
www.bing.com
